/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboards;

import Login.LoginForm;
import database.*;
import javax.swing.*;
import java.awt.event.*;
import java.sql.*;
import utils.ActivityLogger;

/**
 * Admin Dashboard – full control panel.
 * WARNING: Do NOT modify initComponents. The content of this method is always
 * regenerated by the Form Editor.
 *
 * FIXES APPLIED:
 *  - Bug #3 (double-click override): openFacultyAsAdmin() and openStudentAsAdmin()
 *    now open Faculty/StudentDashboard with the isAdminProxy constructor.
 *  - These helpers are called from FacultiesWindow and StudentsWindow via the
 *    pattern shown in the comments below.
 *  - Stats (year-level breakdown) were already correct — no change needed.
 *  - btnStudents and btnFaculties now pass a reference so those windows can
 *    call back into the admin double-click logic.
 */
public class AdminDashboard extends javax.swing.JFrame {

    public AdminDashboard() {
        initComponents();
        loadStats();
    }

    // ── Business logic ────────────────────────────────────────────────────────

    private void loadStats() {
        try {
            String name = Session.getFullName();
            lblAdminName.setText(name);
            lblRole.setText("Role: Administrator");

            try (Connection conn = DatabaseManager.getConnection()) {
                lblTotalStudents .setText(String.valueOf(count(conn, "students")));
                lblTotalFaculty  .setText(String.valueOf(count(conn, "faculty")));
                lblTotalSections .setText(String.valueOf(count(conn, "sections")));
                lblTotalSubjects .setText(String.valueOf(count(conn, "subjects")));

                // Year-level breakdown
                lblY1.setText(String.valueOf(countWhere(conn,"students","year_level=1")));
                lblY2.setText(String.valueOf(countWhere(conn,"students","year_level=2")));
                lblY3.setText(String.valueOf(countWhere(conn,"students","year_level=3")));
                lblY4.setText(String.valueOf(countWhere(conn,"students","year_level=4")));
            }
        } catch (Exception e) {
            System.err.println("AdminDashboard loadStats: " + e.getMessage());
        }
    }

    private int count(Connection conn, String table) throws SQLException {
        ResultSet rs = conn.createStatement().executeQuery("SELECT COUNT(*) FROM " + table);
        return rs.next() ? rs.getInt(1) : 0;
    }

    private int countWhere(Connection conn, String table, String where) throws SQLException {
        ResultSet rs = conn.createStatement().executeQuery("SELECT COUNT(*) FROM " + table + " WHERE " + where);
        return rs.next() ? rs.getInt(1) : 0;
    }

    // ── FIX #3: Admin double-click — open Faculty dashboard with override ─────

    /**
     * Opens a Faculty dashboard in admin-proxy mode for the given faculty's user_id.
     * Call this from FacultiesWindow when the admin double-clicks a row:
     *
     *   table.addMouseListener(new MouseAdapter() {
     *       public void mouseClicked(MouseEvent e) {
     *           if (e.getClickCount() == 2) {
     *               int userId = getSelectedFacultyUserId(); // from your table model
     *               AdminDashboard.openFacultyAsAdmin(userId);
     *           }
     *       }
     *   });
     */
    public static void openFacultyAsAdmin(int facultyUserId) {
        Faculty f = new Faculty(facultyUserId, true);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }

    /**
     * Opens a Student dashboard in admin-proxy mode for the given student's user_id.
     * Call this from StudentsWindow when the admin double-clicks a row:
     *
     *   table.addMouseListener(new MouseAdapter() {
     *       public void mouseClicked(MouseEvent e) {
     *           if (e.getClickCount() == 2) {
     *               int userId = getSelectedStudentUserId(); // from your table model
     *               AdminDashboard.openStudentAsAdmin(userId);
     *           }
     *       }
     *   });
     */
    public static void openStudentAsAdmin(int studentUserId) {
        StudentDashboard sd = new StudentDashboard(studentUserId, true);
        sd.setLocationRelativeTo(null);
        sd.setVisible(true);
    }

    // ── Generated Code ────────────────────────────────────────────────────────

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidebar = new panelDesigns.Panel_AdminSidebar();
        lblSmis = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        jSep1 = new javax.swing.JSeparator();
        btnDash = new color.Button_Admin("a");
        btnSections = new color.Button_Admin("a");
        btnSubjects = new color.Button_Admin("a");
        btnStudents = new color.Button_Admin("a");
        btnAssign = new color.Button_Admin("a");
        btnFaculties = new color.Button_Admin("a");
        btnAnnounce = new color.Button_Admin("a");
        btnProfile = new color.Button_Admin("a");
        btnLogs = new color.Button_Admin("a");
        btnLogout = new color.Button_Admin("");
        jPanelMain = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblAdminName = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        panelStudents = new javax.swing.JPanel();
        lblTotalStudents = new javax.swing.JLabel();
        lblTotStudLbl = new javax.swing.JLabel();
        panelFaculty = new javax.swing.JPanel();
        lblTotalFaculty = new javax.swing.JLabel();
        lblTotFacLbl = new javax.swing.JLabel();
        panelSections = new javax.swing.JPanel();
        lblTotalSections = new javax.swing.JLabel();
        lblTotSecLbl = new javax.swing.JLabel();
        panelSubjects = new javax.swing.JPanel();
        lblTotalSubjects = new javax.swing.JLabel();
        lblTotSubLbl = new javax.swing.JLabel();
        panelYL = new javax.swing.JPanel();
        lblY1Lbl = new javax.swing.JLabel();
        lblY1 = new javax.swing.JLabel();
        lblY2Lbl = new javax.swing.JLabel();
        lblY2 = new javax.swing.JLabel();
        lblY3Lbl = new javax.swing.JLabel();
        lblY3 = new javax.swing.JLabel();
        lblY4Lbl = new javax.swing.JLabel();
        lblY4 = new javax.swing.JLabel();

        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSmis.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblSmis.setText("SMIS");
        sidebar.add(lblSmis, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        lblAdmin.setText("Administrator");
        sidebar.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 120, -1, -1));
        sidebar.add(jSep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 200, 10));

        btnDash.setText("My Dashboard");
        btnDash.setBorderPainted(false);
        btnDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashActionPerformed(evt);
            }
        });
        sidebar.add(btnDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, 30));

        btnSections.setText("Sections");
        btnSections.setBorderPainted(false);
        btnSections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSectionsActionPerformed(evt);
            }
        });
        sidebar.add(btnSections, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 206, 200, 30));

        btnSubjects.setText("Subjects");
        btnSubjects.setBorderPainted(false);
        btnSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubjectsActionPerformed(evt);
            }
        });
        sidebar.add(btnSubjects, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 242, 200, 30));

        btnStudents.setText("Students");
        btnStudents.setBorderPainted(false);
        btnStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentsActionPerformed(evt);
            }
        });
        sidebar.add(btnStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 278, 200, 30));

        btnAssign.setText("Assignments");
        btnAssign.setBorderPainted(false);
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        sidebar.add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 314, 200, 30));

        btnFaculties.setText("Faculties");
        btnFaculties.setBorderPainted(false);
        btnFaculties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacultiesActionPerformed(evt);
            }
        });
        sidebar.add(btnFaculties, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 200, 30));

        btnAnnounce.setText("Announcements");
        btnAnnounce.setBorderPainted(false);
        btnAnnounce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnounceActionPerformed(evt);
            }
        });
        sidebar.add(btnAnnounce, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 386, 200, 30));

        btnProfile.setText("My Profile");
        btnProfile.setBorderPainted(false);
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        sidebar.add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 422, 200, 30));

        btnLogs.setText("Activity Logs");
        btnLogs.setBorderPainted(false);
        btnLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogsActionPerformed(evt);
            }
        });
        sidebar.add(btnLogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 458, 200, 30));

        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        sidebar.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, -1, -1));

        jPanel1.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 710));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelMain.setBackground(new java.awt.Color(232, 240, 254));
        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblWelcome.setText("Welcome,");
        jPanelMain.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lblAdminName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAdminName.setText("Administrator");
        jPanelMain.add(lblAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 200, -1));

        lblRole.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblRole.setText("Role: Administrator");
        jPanelMain.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 58, -1, -1));

        panelStudents.setBackground(new java.awt.Color(21, 101, 192));
        panelStudents.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalStudents.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblTotalStudents.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalStudents.setText("0");
        panelStudents.add(lblTotalStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 15, -1, -1));

        lblTotStudLbl.setForeground(new java.awt.Color(255, 255, 255));
        lblTotStudLbl.setText("Total Students");
        panelStudents.add(lblTotStudLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jPanelMain.add(panelStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 150, 90));

        panelFaculty.setBackground(new java.awt.Color(27, 94, 32));
        panelFaculty.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalFaculty.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblTotalFaculty.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalFaculty.setText("0");
        panelFaculty.add(lblTotalFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 15, -1, -1));

        lblTotFacLbl.setForeground(new java.awt.Color(255, 255, 255));
        lblTotFacLbl.setText("Total Faculty");
        panelFaculty.add(lblTotFacLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jPanelMain.add(panelFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 150, 90));

        panelSections.setBackground(new java.awt.Color(106, 27, 154));
        panelSections.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalSections.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblTotalSections.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalSections.setText("0");
        panelSections.add(lblTotalSections, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 15, -1, -1));

        lblTotSecLbl.setForeground(new java.awt.Color(255, 255, 255));
        lblTotSecLbl.setText("Total Sections");
        panelSections.add(lblTotSecLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jPanelMain.add(panelSections, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 150, 90));

        panelSubjects.setBackground(new java.awt.Color(183, 28, 28));
        panelSubjects.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalSubjects.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblTotalSubjects.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalSubjects.setText("0");
        panelSubjects.add(lblTotalSubjects, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 15, -1, -1));

        lblTotSubLbl.setForeground(new java.awt.Color(255, 255, 255));
        lblTotSubLbl.setText("Total Subjects");
        panelSubjects.add(lblTotSubLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jPanelMain.add(panelSubjects, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 150, 90));

        panelYL.setBackground(new java.awt.Color(255, 255, 255));
        panelYL.setBorder(javax.swing.BorderFactory.createTitledBorder("Students by Year Level"));
        panelYL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblY1Lbl.setText("1st Year:");
        panelYL.add(lblY1Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, 80, -1));

        lblY1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblY1.setText("0");
        panelYL.add(lblY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 25, -1, -1));

        lblY2Lbl.setText("2nd Year:");
        panelYL.add(lblY2Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));

        lblY2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblY2.setText("0");
        panelYL.add(lblY2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        lblY3Lbl.setText("3rd Year:");
        panelYL.add(lblY3Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, 80, -1));

        lblY3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblY3.setText("0");
        panelYL.add(lblY3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 75, -1, -1));

        lblY4Lbl.setText("4th Year:");
        panelYL.add(lblY4Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, -1));

        lblY4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblY4.setText("0");
        panelYL.add(lblY4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jPanelMain.add(panelYL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 215, 300, 135));

        getContentPane().add(jPanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 0, 840, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSideBtn(javax.swing.JPanel p, javax.swing.JButton b, String text, int x, int y, int w) {
        b.setText(text); b.setBorderPainted(false); b.setFocusPainted(false);
        p.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, w, 30));
    }

    private void makeStatCard(javax.swing.JPanel parent, javax.swing.JPanel card,
                               javax.swing.JLabel lblTitle, String title,
                               javax.swing.JLabel lblVal, java.awt.Color bg, int x, int y) {
        card.setBackground(bg);
        card.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 11));
        lblTitle.setForeground(java.awt.Color.WHITE);
        lblTitle.setText(title);
        card.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        lblVal.setFont(new java.awt.Font("Segoe UI", 1, 32));
        lblVal.setForeground(java.awt.Color.WHITE);
        lblVal.setText("0");
        card.add(lblVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 15, -1, -1));
        parent.add(card, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, 150, 90));
    }

    private void addYLRow(javax.swing.JPanel p, javax.swing.JLabel lbl, String t, javax.swing.JLabel val, int x, int y) {
        lbl.setText(t);
        p.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, 80, -1));
        val.setFont(new java.awt.Font("Segoe UI", 1, 14));
        val.setText("0");
        p.add(val, new org.netbeans.lib.awtextra.AbsoluteConstraints(x+90, y, -1, -1));
    }

    private void openWindow(javax.swing.JFrame w) {
        w.setVisible(true);
    }

    // ── Button handlers ───────────────────────────────────────────────────────

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Session.logout();
        dispose();
        JFrame frame = new JFrame("SMIS");
        frame.setSize(739, 500);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setLocationRelativeTo(null);
        frame.add(new LoginForm());
        frame.setVisible(true);
        
        ActivityLogger.endSession();
        Session.logout();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogsActionPerformed
        new windows.ActivityLogsWindow().setVisible(true);
    }//GEN-LAST:event_btnLogsActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        new windows.AdminProfileWindow().setVisible(true);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnAnnounceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnounceActionPerformed
        new windows.AnnouncementsWindow().setVisible(true);
    }//GEN-LAST:event_btnAnnounceActionPerformed

    private void btnFacultiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacultiesActionPerformed
        new windows.FacultiesWindow().setVisible(true);
    }//GEN-LAST:event_btnFacultiesActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        new windows.AssignmentsWindow().setVisible(true);
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsActionPerformed
        new windows.StudentsWindow().setVisible(true);
    }//GEN-LAST:event_btnStudentsActionPerformed

    private void btnSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubjectsActionPerformed
        new windows.SubjectsWindow().setVisible(true);
    }//GEN-LAST:event_btnSubjectsActionPerformed

    private void btnSectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSectionsActionPerformed
        new windows.SectionsWindow().setVisible(true);
    }//GEN-LAST:event_btnSectionsActionPerformed

    private void btnDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashActionPerformed
        loadStats();
    }//GEN-LAST:event_btnDashActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnounce;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnDash;
    private javax.swing.JButton btnFaculties;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogs;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnSections;
    private javax.swing.JButton btnStudents;
    private javax.swing.JButton btnSubjects;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JSeparator jSep1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblAdminName;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSmis;
    private javax.swing.JLabel lblTotFacLbl;
    private javax.swing.JLabel lblTotSecLbl;
    private javax.swing.JLabel lblTotStudLbl;
    private javax.swing.JLabel lblTotSubLbl;
    private javax.swing.JLabel lblTotalFaculty;
    private javax.swing.JLabel lblTotalSections;
    private javax.swing.JLabel lblTotalStudents;
    private javax.swing.JLabel lblTotalSubjects;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblY1;
    private javax.swing.JLabel lblY1Lbl;
    private javax.swing.JLabel lblY2;
    private javax.swing.JLabel lblY2Lbl;
    private javax.swing.JLabel lblY3;
    private javax.swing.JLabel lblY3Lbl;
    private javax.swing.JLabel lblY4;
    private javax.swing.JLabel lblY4Lbl;
    private javax.swing.JPanel panelFaculty;
    private javax.swing.JPanel panelSections;
    private javax.swing.JPanel panelStudents;
    private javax.swing.JPanel panelSubjects;
    private javax.swing.JPanel panelYL;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
