package dashboards;

import Login.LoginForm;
import database.DatabaseManager;
import database.Session;
import javax.swing.*;
import java.sql.*;
import utils.ActivityLogger;

/**
 * Faculty Dashboard.
 * WARNING: Do NOT modify initComponents. The content of this method is always
 * regenerated by the Form Editor.
 */
public class Faculty extends javax.swing.JFrame {
    private int facultyUserId;   // field for faculty ID
    private boolean adminProxy;  // flag for admin proxy mode

    // ── Constructors ──────────────────────────────────────────────────────────

    /** Normal login entry-point — uses Session for the current user. */
    public Faculty() {
        initComponents();
        this.adminProxy = false;
        this.facultyUserId = Session.getProfileId(); // set from Session
        loadUserData();
    }

    /** Constructor for normal faculty login with explicit ID. */
    public Faculty(int facultyUserId) {
        this.facultyUserId = facultyUserId;
        this.adminProxy = false;
        initComponents();
        loadUserData();
    }

    /** Admin override entry-point. */
    public Faculty(int facultyUserId, boolean isAdminProxy) {
        this.facultyUserId = facultyUserId;
        this.adminProxy = isAdminProxy;
        initComponents();
        if (isAdminProxy) {
            btnLogout.setText("Close (Admin)");
            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        }
        loadUserDataForUser(facultyUserId);
    }

    /** Called by admin to flip an existing instance into proxy mode. */
    public void setAsAdminProxy(boolean proxy) {
        this.adminProxy = proxy;
        if (proxy) {
            btnLogout.setText("Close (Admin)");
        }
    }

    // ── Business logic ────────────────────────────────────────────────────────

    /** Loads stats for the currently-logged-in faculty (normal flow). */
    private void loadUserData() {
        lblFirstName.setText(Session.getFirstName());
        lblLastName.setText(Session.getLastName());
        lblRoleTag.setText("Faculty");

        int profileId = Session.getProfileId();
        if (profileId <= 0) return;

        loadStatsForFacultyId(profileId);
    }

    /** Loads stats by looking up the faculty row from a given users.id. */
    private void loadUserDataForUser(int userId) {
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement ps = conn.prepareStatement(
                 "SELECT first_name, last_name, id FROM faculty WHERE user_id=?")) {
            ps.setInt(1, userId);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                lblFirstName.setText(rs.getString("first_name"));
                lblLastName.setText(rs.getString("last_name"));
                lblRoleTag.setText("Faculty  [Admin View]");
                loadStatsForFacultyId(rs.getInt("id"));
            }
        } catch (SQLException e) {
            System.err.println("Faculty loadUserDataForUser: " + e.getMessage());
        }
    }

    /** Loads section/subject/student counts for a faculty.id. */
    private void loadStatsForFacultyId(int facultyId) {
        try (Connection conn = DatabaseManager.getConnection()) {
            PreparedStatement ps = conn.prepareStatement(
                "SELECT COUNT(DISTINCT section_id), COUNT(DISTINCT subject_id) " +
                "FROM faculty_subjects WHERE faculty_id=?");
            ps.setInt(1, facultyId);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                lblSections.setText(String.valueOf(rs.getInt(1)));
                lblSubjects.setText(String.valueOf(rs.getInt(2)));
            }

            ps = conn.prepareStatement(
                "SELECT COUNT(DISTINCT s.id) " +
                "FROM students s " +
                "JOIN faculty_subjects fs ON fs.section_id = s.section_id " +
                "WHERE fs.faculty_id = ?");
            ps.setInt(1, facultyId);
            rs = ps.executeQuery();
            if (rs.next()) lblStudents.setText(String.valueOf(rs.getInt(1)));

            lblFacultyId.setText(String.valueOf(facultyId));
        } catch (SQLException e) {
            System.err.println("Faculty loadStatsForFacultyId: " + e.getMessage());
        }
    }

    // ── Generated Code ────────────────────────────────────────────────────────

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new panelDesigns.Panel_FacultySidebar();
        lblSmis = new javax.swing.JLabel();
        lblFacTag = new javax.swing.JLabel();
        jSep1 = new javax.swing.JSeparator();
        btnDash = new color.Button_Faculty("");
        btnSections = new color.Button_Faculty("");
        btnSubjects = new color.Button_Faculty("");
        btnStudents = new color.Button_Faculty("");
        btnRecord = new color.Button_Faculty("");
        btnAnnounce = new color.Button_Faculty("");
        btnProfile = new color.Button_Faculty("");
        btnLogs = new color.Button_Faculty("");
        btnLogout = new javax.swing.JButton();
        jPanelMain = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblRoleTag = new javax.swing.JLabel();
        panelSec = new javax.swing.JPanel();
        lblSections = new javax.swing.JLabel();
        lblSecLbl = new javax.swing.JLabel();
        panelSub = new javax.swing.JPanel();
        lblSubjects = new javax.swing.JLabel();
        lblSubLbl = new javax.swing.JLabel();
        panelStud = new javax.swing.JPanel();
        lblStudents = new javax.swing.JLabel();
        lblStudLbl = new javax.swing.JLabel();
        panelFid = new javax.swing.JPanel();
        lblFacultyId = new javax.swing.JLabel();
        lblFidLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSmis.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblSmis.setText("SMIS");
        sidebar.add(lblSmis, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        lblFacTag.setText("Faculty");
        sidebar.add(lblFacTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 120, -1, -1));
        sidebar.add(jSep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 200, 10));

        btnDash.setText("My Dashboard");
        btnDash.setBorderPainted(false);
        btnDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashActionPerformed(evt);
            }
        });
        sidebar.add(btnDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, 30));

        btnSections.setText("My Sections");
        btnSections.setBorderPainted(false);
        btnSections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSectionsActionPerformed(evt);
            }
        });
        sidebar.add(btnSections, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 206, 200, 30));

        btnSubjects.setText("My Subjects");
        btnSubjects.setBorderPainted(false);
        btnSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubjectsActionPerformed(evt);
            }
        });
        sidebar.add(btnSubjects, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 242, 200, 30));

        btnStudents.setText("Students");
        btnStudents.setBorderPainted(false);
        btnStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentsActionPerformed(evt);
            }
        });
        sidebar.add(btnStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 278, 200, 30));

        btnRecord.setText("Class Record");
        btnRecord.setBorderPainted(false);
        btnRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordActionPerformed(evt);
            }
        });
        sidebar.add(btnRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 314, 200, 30));

        btnAnnounce.setText("Announcements");
        btnAnnounce.setBorderPainted(false);
        btnAnnounce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnounceActionPerformed(evt);
            }
        });
        sidebar.add(btnAnnounce, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 200, 30));

        btnProfile.setText("My Profile");
        btnProfile.setBorderPainted(false);
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        sidebar.add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 386, 200, 30));

        btnLogs.setText("Activity Logs");
        btnLogs.setBorderPainted(false);
        btnLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogsActionPerformed(evt);
            }
        });
        sidebar.add(btnLogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 422, 200, 30));

        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        sidebar.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, -1, -1));

        getContentPane().add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 252, 700));

        jPanelMain.setBackground(new java.awt.Color(232, 244, 232));
        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFirstName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFirstName.setText("First");
        jPanelMain.add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblLastName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLastName.setText("Last");
        jPanelMain.add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        lblRoleTag.setText("Faculty");
        jPanelMain.add(lblRoleTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        panelSec.setBackground(new java.awt.Color(102, 102, 255));
        panelSec.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSections.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSections.setText("0");
        panelSec.add(lblSections, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 22, -1, -1));

        lblSecLbl.setText("Total Sections");
        panelSec.add(lblSecLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 65, -1, -1));

        jPanelMain.add(panelSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, 100));

        panelSub.setBackground(new java.awt.Color(204, 255, 102));
        panelSub.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSubjects.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSubjects.setText("0");
        panelSub.add(lblSubjects, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 22, -1, -1));

        lblSubLbl.setText("Total Subjects");
        panelSub.add(lblSubLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 65, -1, -1));

        jPanelMain.add(panelSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 160, 100));

        panelStud.setBackground(new java.awt.Color(51, 255, 153));
        panelStud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStudents.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblStudents.setText("0");
        panelStud.add(lblStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 22, -1, -1));

        lblStudLbl.setText("Total Students");
        panelStud.add(lblStudLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 65, -1, -1));

        jPanelMain.add(panelStud, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 160, 100));

        panelFid.setBackground(new java.awt.Color(102, 102, 255));
        panelFid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFacultyId.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFacultyId.setText("0");
        panelFid.add(lblFacultyId, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 22, -1, -1));

        lblFidLbl.setText("Faculty ID");
        panelFid.add(lblFidLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 65, -1, -1));

        jPanelMain.add(panelFid, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 160, 100));

        getContentPane().add(jPanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 0, 750, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // </editor-fold>

    // ── Button handlers ───────────────────────────────────────────────────────

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        if (adminProxy) { dispose(); return; }
        Session.logout();
        dispose();
        JFrame frame = new JFrame("SMIS");
        frame.setSize(739, 500);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setLocationRelativeTo(null);
        frame.add(new LoginForm());
        frame.setVisible(true);

        ActivityLogger.endSession();
        Session.logout();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashActionPerformed
        loadUserData();
    }//GEN-LAST:event_btnDashActionPerformed

    private void btnSectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSectionsActionPerformed
        new windows.FacultySectionsWindow(this.facultyUserId).setVisible(true);
    }//GEN-LAST:event_btnSectionsActionPerformed

    private void btnSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubjectsActionPerformed
        new windows.FacultySubjectsWindow(this.facultyUserId).setVisible(true);
    }//GEN-LAST:event_btnSubjectsActionPerformed

    private void btnStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsActionPerformed
        new windows.FacultyStudentsWindow(this.facultyUserId).setVisible(true);
    }//GEN-LAST:event_btnStudentsActionPerformed

    private void btnRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordActionPerformed
        new windows.ClassRecordWindow(this.facultyUserId).setVisible(true);
    }//GEN-LAST:event_btnRecordActionPerformed

    private void btnAnnounceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnounceActionPerformed
        new windows.AnnouncementsWindow(this.facultyUserId).setVisible(true);
    }//GEN-LAST:event_btnAnnounceActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        new windows.FacultyProfileWindow(this.facultyUserId).setVisible(true);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogsActionPerformed
        new windows.ActivityLogsWindow(this.facultyUserId).setVisible(true);
    }//GEN-LAST:event_btnLogsActionPerformed

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException |
                 IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName())
                .log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new Faculty().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnounce;
    private javax.swing.JButton btnDash;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogs;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnRecord;
    private javax.swing.JButton btnSections;
    private javax.swing.JButton btnStudents;
    private javax.swing.JButton btnSubjects;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JSeparator jSep1;
    private javax.swing.JLabel lblFacTag;
    private javax.swing.JLabel lblFacultyId;
    private javax.swing.JLabel lblFidLbl;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblRoleTag;
    private javax.swing.JLabel lblSecLbl;
    private javax.swing.JLabel lblSections;
    private javax.swing.JLabel lblSmis;
    private javax.swing.JLabel lblStudLbl;
    private javax.swing.JLabel lblStudents;
    private javax.swing.JLabel lblSubLbl;
    private javax.swing.JLabel lblSubjects;
    private javax.swing.JPanel panelFid;
    private javax.swing.JPanel panelSec;
    private javax.swing.JPanel panelStud;
    private javax.swing.JPanel panelSub;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
  }